- name: Copying files over
  ansible.builtin.copy:
    src: /home/{{ host_username }}/repos/iac_base/ansible/package
    dest: /home/{{ username }}

- name: Create media folder
  ansible.builtin.file:
    path:  media
    state: directory
    mode: '0755'

- name: Mount network share
  mount:
    src: //192.168.4.35/share
    path: /home/{{ username }}/media
    fstype: cifs
    opts: 'credentials=/home/{{ username }}/package/.creds'
    state: mounted
